### ISSUE TITLE
Suggested Code Improvement

### ISSUE THREAD

**Issue by dgt12** [TeHikuMedia/nga-kupu#9]
Hi there,

I noticed an issue on line 10 of the "kupu_tūtira" file, where it is importing the method "kōmiri_kupu" (with a macron) but when I looked into the file __init__.py in the taumahi folder the method seems to be called komiri_kupu (without a macron).

To fix this, you could change line 10 of kupu_tūtira to:
from taumahi import komiri_kupu, nahanaha 

And also change line 50 to:
tuhi_puta_tuhinga(kōwhiri, nahanaha(komiri_kupu(kupu_tōkau)[0].keys()))

**Comment by Br3nda** [comment]
I've pull this into a pull request on #10

**Comment by edwardabraham** [comment]
Hi @mathematiguy  could you check this!

**Comment by mathematiguy** [comment]
Fixed by #10 - thanks for spotting!
